### ISSUE TITLE
Add acmart packages

### ISSUE THREAD

**Issue by nottsknight** [nottsknight/uon-thesis-template#1]
Identify the packages used in the acmart document class, and add those that are missing

**Comment by psxjpm** [comment]
Added the following missing packages from the acmart document class to README.md 

- array
- fancyvrb
- hypdoc
- libertine
- longtable
- newtxmath 
- zi4

Some of the ACM packages substitute default packages you have: nextxmath and zi4 substitute amsmath and inconsolata respectively
